### ISSUE TITLE
recaptcha v2 integration

### ISSUE THREAD

**Issue by willyfromtheblock** [grantisu/Sericata#1]
Hey there,

recaptcha v1 is going to be shut down in a couple of days.

Is it possible to implement a v2 compatible lib?

Sorry, but I hardly know enough python to make small adjustments and couldn't find a suitable lib.

Willy

**Comment by grantisu** [comment]
Sorry, this project has been dead for about four years.

I would *strongly* suggest not using this code in a situation where captchas are needed unless you "know enough python to make small adjustments".

If you want to put in the effort to [figure out updating the captcha](https://developers.google.com/recaptcha/docs/display) (should be able to just drop the library and inline the sample code) plus maintaining whatever else breaks, I'd be happy to update the readme with a link to your fork as the "official" version. :)
